# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets

import sys
import .analyze 
from PyQt5 import QtCore, QtGui, QtWidgets
from windowdesign import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)###########
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 26))
        self.menubar.setObjectName("menubar")
#menubarımız
        self.menuGenel = QtWidgets.QMenu(self.menubar)#########
        self.menuGenel.setObjectName("menuGenel")
        self.menuSe_enekler = QtWidgets.QMenu(self.menubar)
        self.menuSe_enekler.setObjectName("menuSe_enekler")
        self.menuAlanlar_E_leme = QtWidgets.QMenu(self.menubar)
        self.menuAlanlar_E_leme.setObjectName("menuAlanlar_E_leme")
        self.menuCategory_Mapping = QtWidgets.QMenu(self.menubar)
        self.menuCategory_Mapping.setObjectName("menuCategory_Mapping")
        self.menuCron = QtWidgets.QMenu(self.menubar)
        self.menuCron.setObjectName("menuCron")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSe_enekler = QtWidgets.QAction(MainWindow)
        self.actionSe_enekler.setObjectName("actionSe_enekler")
#
        self.menubar.addAction(self.menuGenel.menuAction())
        self.menubar.addAction(self.menuSe_enekler.menuAction())
        self.menubar.addAction(self.menuAlanlar_E_leme.menuAction())
        self.menubar.addAction(self.menuCategory_Mapping.menuAction())
        self.menubar.addAction(self.menuCron.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuGenel.setTitle(_translate("MainWindow", "Genel"))
        self.menuSe_enekler.setTitle(_translate("MainWindow", "Seçenekler"))
        self.menuAlanlar_E_leme.setTitle(_translate("MainWindow", "Alanları Eşleme"))
        self.menuCategory_Mapping.setTitle(_translate("MainWindow", "Category Mapping"))
        self.menuCron.setTitle(_translate("MainWindow", "Cron"))
     #   self.actionSe_enekler.setText(_translate("MainWindow", "Seçenekler"))
    #    self.actionsefsg.setText(_translate("MainWindow", "sefsg"))
   #     self.actionsgesge.setText(_translate("MainWindow", "sgesge"))
  #      self.actiondrhdhr.setText(_translate("MainWindow", "drhdhr"))
 #       self.actiondrhdjr.setText(_translate("MainWindow", "drhdjr"))
#        self.actionftjfj.setText(_translate("MainWindow", "ftjfj"))
